### ISSUE TITLE
Mint.TransportError: :closed

### ISSUE THREAD

**Issue by NeilMenne** [keathley/finch#62] opened 2020-06-18 19:07 UTC
I am using `Finch` in a service that relies on a remote service for data, but I am doing a fair amount of caching and other work at my service to avoid having to make this remote call too often for performance reasons.

As a result, we are periodically seeing this socket close error. A [related issue on Mint](https://github.com/elixir-mint/mint/issues/255) points to different defaults being necessary for `:conn_opts` as part of the initial pool configuration. I don't know if it's actually the fix, but any possibility that this socket being closed can be detected behind the scenes in `Finch`? The ideal would be that if a connection gets closed due to inactivity that it wouldn't be surfaced when making a later request.

Version Information:
Finch: 0.2.0
Mint: 1.1.0

**Comment by josevalim** [comment] 2020-06-23 21:33
Definitely. On checkout, if the connection is closed, we need to automatically reconnect without pushing errors upstream. My understanding is that transferring between process will fail if the connection is closed. Is this correct @whatyouhide?

**Comment by josevalim** [comment] 2020-06-23 21:46
Actually, it seems we already reconnect if the socket is closed. Can you provide an example that reproduces the issue? I am thinking it is one of the issues where it only says closed when we write to it.

**Comment by sneako** [comment] 2020-06-23 22:18
I am actually seeing this error in my application too, but only around 50 per second, when I am currently making > 100,000 requests/s, so it hasn't been a very high priority for me, but I definitely agree that we should be able to prevent it. I'll take another stab at making a reproducible example this evening.

**Comment by josevalim** [comment] 2020-06-23 22:22
Do you know if it is happening when we send the request? That would be my bet. If we can identify the source, then it should be a (hopefully) easy fix.

**Comment by sneako** [comment] 2020-06-23 22:29
I assume that is where it is happening as well. I can try whipping up a temporary fork on Finch, wrapping the errors, to nail down exactly where this comes from.

**Comment by keathley** [comment] 2020-06-23 23:15
I think it’s possible that the connection is being closed after it’s checked back into the pool. Then the next time we try to use it the connection returns an error. That’s my hypothesis

**Comment by sneako** [comment] 2020-06-23 23:25
Looks like this error is always happening when we are waiting for the response actually, here: https://github.com/keathley/finch/pull/65/files#diff-c3126e24dc4c2613caa9bec21852ec5aR109

**Comment by sneako** [comment] 2020-06-23 23:37
> I think it’s possible that the connection is being closed after it’s checked back into the pool. Then the next time we try to use it the connection returns an error. That’s my hypothesis

I would expect Finch to try to checkout a new worker from NimblePool if an error occurred during the handle_checkout callback

**Comment by josevalim** [comment] 2020-06-24 07:35
@sneako it is happening in the response before it sends the headers and stuff? If so... then yeah, Finch is correct in return `:closed`.

**Comment by sneako** [comment] 2020-06-24 16:50
I can do another test later today to check if we have received any part of the response yet when this happens.

**Comment by sneako** [comment] 2020-06-24 18:26
I deployed this branch: https://github.com/keathley/finch/compare/track-closed-error and can confirm that in my case, the closed error is returned before any part of the response has been received at all (always getting "req_recv_empty"), so it seems that Finch is behaving correctly.

**Comment by NeilMenne** [comment] 2020-06-24 18:56
I will try to carve out some time to deploy that branch with some additional tracing/logging information.

In the short term, we had to switch to `HTTPoison` since this appears to be unique to `Finch` in our deployed environment.

**Comment by NeilMenne** [comment] 2020-06-25 16:04
We have confirmed that this is the error we're seeing as well with the linked branch. While it may seem that it's behaving correctly, under identical workloads HTTPoison does not exhibit this behavior and Finch has a much more forgiving default timeout for receive (`15_000` I believe) that we are _not_ approaching.

Is it possible that there are some timing issues around the connection management? If I check out a connection and is due to be reclaimed due to inactivity before I actually send the data for example, it would be closed by the time I try to send my actual GET request.

**Comment by josevalim** [comment] 2020-06-25 16:57
@NeilMenne are your errors happening before sending the request or before receiving the response or after sending the response?

**Comment by NeilMenne** [comment] 2020-06-25 21:54
I am working on putting it back in place with more thorough telemetry hooks to tell the difference. When I have a sample, I will have an answer!

**Comment by NeilMenne** [comment] 2020-06-25 22:13
Here lies the order of events as telemetry dumped them, so it looks like it's while waiting for the response but well within the response window as the whole thing happens in about 3 ms. I did try to find relevant logs on the other service as well to correlate, but it appears to have never gotten there.

All of this on a re-used connection too...

```
21:56:10.482 request_id=FhvoLFbo0yed2sUAAAlk [info] [:finch, :queue, :start] | %{system_time: 1593122170482380015} | %{host: "redacted", pool: #PID<0.5073.0>, port: 443, scheme: :https}
21:56:10.482 request_id=FhvoLFbo0yed2sUAAAlk [info] [:finch, :queue, :stop] | %{duration: 395655, idle_time: 558151263389} | %{host: "redacted", pool: #PID<0.5073.0>, port: 443, scheme: :https}
21:56:10.482 request_id=FhvoLFbo0yed2sUAAAlk [info] [:finch, :reused_connection] | %{} | %{host: "redacted", port: 443, scheme: :https}
21:56:10.484 request_id=FhvoLFbo0yed2sUAAAlk [info] [:finch, :request, :start] | %{system_time: 1593122170482943249}**%{host: "redacted", path: "/redactedpath", port: 443, scheme: :https}
21:56:10.485 request_id=FhvoLFbo0yed2sUAAAlk [info] [:finch, :request, :stop] | %{duration: 1857550} | %{host: "redacted", path: "/redactedpath", port: 443, scheme: :https}
21:56:10.485 request_id=FhvoLFbo0yed2sUAAAlk [info] [:finch, :response, :start] | %{system_time: 1593122170485031014} | %{host: "redacted", path: "/redactedpath", port: 443, scheme: :https}
21:56:10.485 request_id=FhvoLFbo0yed2sUAAAlk [info] [:finch, :response, :stop] | %{duration: 714219} | %{error: %Mint.TransportError{reason: :closed}, host: "redacted", path: "/redactedpath", port: 443, scheme: :https}
```

**Comment by josevalim** [comment] 2020-06-25 22:27
Beautiful. Did it send any response at all? Like headers and statuses?

**Comment by NeilMenne** [comment] 2020-06-25 22:40
> Beautiful. Did it send any response at all? Like headers and statuses?

There was nothing that I could find. if you have any additional information that I can track, I'm maintaining a branch for this now.

**Comment by sneako** [comment] 2020-06-25 22:50
Thanks for looking in to this with us @NeilMenne ! I have put together this branch here: https://github.com/keathley/finch/compare/track-closed-error

Using this branch, Finch will return a 3 element tuple on error, where the second element will be an atom or binary, telling us if any part of the response at all was returned before the :closed error.

**Comment by NeilMenne** [comment] 2020-06-25 22:52
It's the the req_recv_empty error

**Comment by sneako** [comment] 2020-06-25 22:53
Ah right ok, so that means that none of the response was received at all, just like what I saw in my application. 🤔

**Comment by NeilMenne** [comment] 2020-06-25 22:54
indeed. only happens to reused connections so far

**Comment by sneako** [comment] 2020-06-25 22:59
So I guess that means that both setting the mode on the connection and transferring the owner of the connection can succeed even in the socket has been closed...

**Comment by NeilMenne** [comment] 2020-06-25 23:01
Yeah, that sounds feasible.

**Comment by josevalim** [comment] 2020-06-25 23:25
It may be that the connection was closed for write on the other side, which is why it happens. We could automatically retry but we may end-up sending the request twice in some cases. We would need to investigate to make sure what is the best way forward.

**Comment by NeilMenne** [comment] 2020-06-26 00:30
Yeah, I don't think you can reasonably do that; however, if we had some insight into the TCP protocol for this, we could tell more information. Things like keep-alive (which is ostensibly being stripped before I can log it or is not being requested by default) would be contributing factors.

At the TCP protocol level, we _should_ get a FIN packet or similar graceful disconnect (depending on the varying levels of abstraction we're interacting with) under normal circumstances. As the remote service is not dying or thrashing when this is happening, it seems like it could be something like that kind of information being ignored/delayed due to having the connection checked out in the client's code.

**Comment by josevalim** [comment] 2020-06-26 00:53
Oh, connection: close! Can you please try this branch? https://github.com/keathley/finch/pull/66

**Comment by NeilMenne** [comment] 2020-06-26 01:27
yeah, i'll get it deployed tomorrow and i'll post results if @sneako doesn't get there first

**Comment by sneako** [comment] 2020-06-26 01:58
Ah that is interesting. We do have a test case for 'connection: close' here: https://github.com/keathley/finch/blob/master/test/finch_test.exs#L202 We should probably increase the iterations there as well, because it only does 10 iterations, with a pool size of 10, so we don't see what happens when we try to reuse a closed connection, but even increasing it 100, always passes locally.

I wonder if we actually need to look for the header here: https://github.com/keathley/finch/pull/66/files#diff-c3126e24dc4c2613caa9bec21852ec5aR143 or if `Mint.HTTP.open?/1` would be enough. I'll try out both

**Comment by sneako** [comment] 2020-06-26 02:40
It does seem that Mint is closing the connection itself when it encounters this header: https://github.com/elixir-mint/mint/blob/9b12d2f3cd53b45864460203f953c202ae6c6a54/lib/mint/http1.ex#L812

I am still trying out the branch though and will post results shortly

**Comment by sneako** [comment] 2020-06-26 02:47
Yeah, unfortunately, #66 does not make a difference ☹️

**Comment by padma0** [comment] 2020-08-12 10:40
Hi, has there been any progress? I found this error in my application too…

**Comment by ericmj** [comment] 2020-08-12 10:58
This error is somewhat expected in any network application since networks are unreliable. So just to clarify this is only an issue stemming from Mint/Finch if there is a high enough error rate that is not related to inherit network unreliability.

**Comment by keathley** [comment] 2020-08-13 14:34
@padma0 Part of the "problem" is that Mint + Finch doesn't do anything to mask this error from you, by issuing retries on your behalf or anything like that. I don't believe that it would be a good choice for us to attempt to hide these issues from the user since an http request may not be idempotent and may not be safe to retry. I'm not sure if this is consistent with other http clients in the elixir/erlang ecosystem though. Surfacing these errors may feel like an issue because they're inconsistent with how other clients are behaving. But I believe surfacing the error is the right approach for users.

At this point, I believe we've investigated this enough. If someone discovers that there's a bug in Mint or something feel free to post that information here. I'm going to close this for now though.

**Comment by mijia** [comment] 2020-08-14 02:08
Hi, sorry to bother you guys again, I'm in the same team with padma0. 

Just want to add some information on this problem. We were using Finch to make http requests from A service to B service and they are both written in Elixir/Phoenix. We are not going through a lot of web hits everyday, but always found the connections were closed while sending requests to B service. Yesterday we found Service B would close the connection from her side using netstat monitoring so we did dig into the configuration of the cowboy and adjusted idle_timeout, inactivity_timeout to 600s on service B. Until now, we don't see that problem again, (finger crossed).

So we don't know if this information could help the team, just want to make it clear from our experience.
And yeah, we added the retries when encountered this :closed problem. But still felt this quite confusing.
Thank you very much.

**Comment by keathley** [comment] 2020-08-14 16:49
@mijia No worries :).

Just for clarity, was this with http/1.1 or http/2? It's possible that we're still not receiving the connection closed signal while the connection is checked into the pool and we're failing to re-open it. I've been trying to find a minimal case to reproduce this, but so far I haven't been able to. I have a new idea that I can try out though.

**Comment by keathley** [comment] 2020-08-14 19:47
Any other input you could give me about your network stack would also be super helpful.

**Comment by mijia** [comment] 2020-08-15 01:56
@keathley Thanks a lot. We use the http/1.1 pool for finch. We cannot reproduce this problem with our local setup either. But in our Kubernetes env both development and production env, we can find this problem. Service A and B are in the same K8S namespace, and exposed as the k8s service, so they can be connected or routed via the k8s DNS service and connect each other directly.

**Comment by keathley** [comment] 2020-09-18 14:43
For anyone who finds this issue in the future, I was able to resolve this in our stacks by ensuring that cowboy's idle connection timeout was greater than the proxies that sit in front of cowboy. Since I was able to track all of those down, I haven't seen this error manifest.

**Comment by ashutoshrishi** [comment] 2020-09-19 06:05
@keathley we have had the cowboy error recently too and did the same configurations. But please correct be if I am wrong, that's a fix on the server end of a HTTP request you make to your servers right? 

We are seeing intermittent errors of `(Mint.TransportError) socket closed` for requests made to an external service like AWS S3 (via ExAws) and Lambda (via ExAws) for which we have no serverside controls to set. I am still trying to re-produce this locally by reducing pool sizes and trying as many requests as I can.

We have had similar problems in a rust HTTP library (which was also new) with AWS and Turnitin APIs. We didn't diagnose the issue completely then, but from our research we found out about Connection re-use limits on S3 and Lambda (around 100 requests per connection). When S3 closes the connection, the rust library just failed in handling that. But nodejs AWS libraries never throw this error (I am assuming because of maturity and in-built retries).

Anyways, back on topic: We have opened pools to Lambda's hostname and Turnitin API. Our throughput is not super high, but  we see `(Mint.TransportError) socket closed`  in production. Hoping to properly diagnose it this time. Do you suggest we implement our own rety mechanisms in this case?

**Comment by keathley** [comment] 2020-09-22 14:09
I've also seen this when calling other services through fastly and other caching or proxy layers. Everything points to this being a legitimate socket closed error. Unfortunately, I can't work out _why_ it happens so it's hard to give a definitive answer on how to mitigate it. I believe that the only real remediation we have right now is to issue retries. If you discover the specific reasons why this is happening I'd love to hear about it :).

**Comment by ashutoshrishi** [comment] 2020-09-23 01:20
I had to go back to `HTTPoison` in Production as there were too many errors even with little throughput. But I never see them while running on my local machine. I have a big suspicion is the AWS networking, especially AWS NAT gateway's `idle_timeout` and connection management. 

I will setup up a debug environment in our production network so that I can log better and take tcpdumps over the weekend. Quite keen to have some resolution to this.

Also I don't think request retries helped. ExAWS retries with backoff and in most cases all of the retries failed with the same `(Mint.TransportError) socket closed)`. 

Before going back to `HTTPoison`, I also tried `mojito` and quickly ran into `%Mint.HTTPError{module: Mint.HTTP2, reason: :closed_for_writing}` https://github.com/appcues/mojito/issues/70. Mojito does have some form of [retry on connection close](https://github.com/appcues/mojito/blob/abfbedceea04bbdd66a1bbe20d3cb22b10642039/lib/mojito/pool/poolboy/single.ex#L115). 

Referring to this [AWS documentation on NAT gateway timeout and logging](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway-cloudwatch.html), I can see that the `IdleTimeoutCount` for my production gateways is not zero.

> A value greater than zero indicates that there are connections that have been moved to an idle state. If the value for IdleTimeoutCount increases, it may indicate that clients behind the NAT gateway are re-using stale connections.

Again, I'll investigate properly at a later stage. Thanks for the help!

**Comment by keathley** [comment] 2020-09-23 03:24
Sounds good @ashutoshrishi. Thanks for continuing to look into it. It seems like it'll be either an issue in Mint or a configuration thing. I'd really like to figure out what hackney is doing under the hood to resolve this. It definitely feels like something to do with idle connections being closed and not being correctly re-opened. For that reason, I'm betting that part of the reason you're seeing this is *because* there's not enough throughput.

Let me know if I can help dig in any more.

**Comment by acco** [comment] 2020-09-28 02:46
Hey @ashutoshrishi - any updates here?

I think you're on to something with your NAT gateway theory. I am able to reliably reproduce on my EC2 ECS servers, and my setup is pretty vanilla - save for a NAT gateway for outgoing requests.

See comment: https://github.com/appcues/mojito/issues/70#issuecomment-699735160

As you'll see in that comment, I can't reproduce in curl - haven't tried any other HTTP libs yet.

> It definitely feels like something to do with idle connections being closed and not being correctly re-opened. For that reason, I'm betting that part of the reason you're seeing this is because there's not enough throughput.

@keathley Yes, this feels right. It has a "warm-up" characteristic.

**Comment by keathley** [comment] 2020-09-28 17:34
I've found an issue in how mint handles connections after streaming. Its possible that this is related to the issues we've been seeing. I can definitely hypothesize ways that this would result in issues on our end, although I'm not convinced that this is the root issue.

**Comment by keathley** [comment] 2020-09-28 17:52
I also may have found an issue in how the http1 pool is handling errors after a receive. I'm going to do some experimentation to confirm.

**Comment by keathley** [comment] 2020-09-28 19:17
re-opening this until the issues in Mint are fixed.

**Comment by keathley** [comment] 2020-09-28 19:30
> I also may have found an issue in how the http1 pool is handling errors after a receive. I'm going to do some experimentation to confirm.

To follow up on this, my hypothesis was that if a server finishes a response and closes a connection, Mint could return an error (since it detects that the connection is closed it returns an error). In that scenario, we would have access to the responses in the error tuple that mint returns from `recv`. We would need to see if the response was complete and return it if so. But, I haven't been able to show that that can happen. Looking at Mint's code, I still believe it _can_ happen. But I haven't been able to accomplish it. If this is what is happening, we would expect to see the errors manifest after consuming most of the response. Based on the notes above, when @NeilMenne and @sneako saw this error they received none of the response body. That would seem to indicate that the main culprit is the Mint issue after performing a `recv`.

At this point, I'm going to work on building a mock http1 webserver so I get a little more control over the underlying tcp connections. Hopefully that'll make it a little easier to induce some of these failures.

**Comment by acco** [comment] 2020-10-01 19:35
Closing the loop on my end, https://github.com/elixir-mint/mint/pull/280 seems to have done the trick for me. Thanks all! 🙏

**Comment by keathley** [comment] 2020-10-02 14:27
Alright, going to re-close this now that the fix has landed in Mint.

**Closed by keathley** 2020-10-02 14:27 UTC

**Comment by derekkraan** [comment] 2022-03-28 12:27
Hoping the following code snippet can help the next person who stumbles upon this issue while googling:

```elixir
  defp do_request(request, pool_name, opts, start_time \\ :erlang.monotonic_time(:millisecond)) do
    case Finch.request(request, pool_name, opts) do
      {:ok, response} ->
        {:ok, response}

      {:error, %Mint.TransportError{} = error} ->
        transport_retry_timeout =
          Keyword.get(opts, :transport_retry_timeout, @default_transport_retry_timeout)

        if :erlang.monotonic_time(:millisecond) < start_time + transport_retry_timeout do
          Logger.warn(fn -> "retrying request, reason: #{inspect(error)}" end)
          do_request(request, pool_name, opts, start_time)
        else
          {:error, error}
        end

      {:error, error} ->
        {:error, error}
    end
  end
```

**Comment by jadlr** [comment] 2022-09-20 08:39
I'm having exactly this problem with the newest versions of finch (0.13.0) and mint (1.4.2). We're using finch in default configuration to call all sorts of APIs. A lot of calls fail with `%Mint.TransportError{reason: :closed}`

**Comment by AHBruns** [comment] 2022-12-09 19:48
Just wanted to add that we are too. Interestingly, it seems to be a cold start issue as the second request (we implement job retries) seems to always succeed.

**Comment by AHBruns** [comment] 2022-12-09 19:50
For example, this is the logs from an Oban job that calls an external service:
```
19:44:24.549 [info] {"args":{"contact_id":632851,"portal_id":7712148},"attempt":1,"event":"job:start","id":923,"max_attempts":2,"meta":{},"queue":"default","source":"oban","system_time":1670615064549808298,"tags":[],"worker":"Grimoire.LeadRanking.Workers.RankContactWorker"}
19:44:24.558 [info] {"args":{"contact_id":632851,"portal_id":7712148},"attempt":1,"duration":2333,"error":"** (MatchError) no match of right hand side value: {:error, %Mint.TransportError{reason: :closed}}","event":"job:exception","id":923,"max_attempts":2,"meta":{},"queue":"default","queue_time":-1104483,"source":"oban","state":"failure","tags":[],"worker":"Grimoire.LeadRanking.Workers.RankContactWorker"}
19:44:39.213 request_id=Fy83kDDzUB2AxBAAACdh [info] GET /status/health
19:44:39.214 request_id=Fy83kDDzUB2AxBAAACdh [info] Sent 200 in 193µs
19:44:39.216 request_id=Fy83kDEcv3J9GUMAADBi [info] GET /status/health
19:44:39.216 request_id=Fy83kDEcv3J9GUMAADBi [info] Sent 200 in 234µs
19:44:39.236 request_id=Fy83kDJF32WPO7kAACdx [info] GET /status/health
19:44:39.236 request_id=Fy83kDJF32WPO7kAACdx [info] Sent 200 in 222µs
19:44:40.217 request_id=Fy83kGzETxlraM8AADBy [info] GET /status/health
19:44:40.217 request_id=Fy83kGzETxlraM8AADBy [info] Sent 200 in 178µs
19:44:40.247 request_id=Fy83kG6PrhQxypEAADCC [info] GET /status/health
19:44:40.247 request_id=Fy83kG6PrhQxypEAADCC [info] Sent 200 in 314µs
19:44:40.266 request_id=Fy83kG-n-wV1D8MAADCS [info] GET /status/health
19:44:40.266 request_id=Fy83kG-n-wV1D8MAADCS [info] Sent 200 in 364µs
19:44:42.479 [info] {"args":{"contact_id":632851,"portal_id":7712148},"attempt":2,"event":"job:start","id":923,"max_attempts":2,"meta":{},"queue":"default","source":"oban","system_time":1670615082479194634,"tags":[],"worker":"Grimoire.LeadRanking.Workers.RankContactWorker"}
19:44:43.231 [info] {"args":{"contact_id":632851,"portal_id":7712148},"attempt":2,"duration":747632,"event":"job:stop","id":923,"max_attempts":2,"meta":{},"queue":"default","queue_time":923030,"source":"oban","state":"success","tags":[],"worker":"Grimoire.LeadRanking.Workers.RankContactWorker"}
```

**Comment by jadlr** [comment] 2022-12-11 11:05
The issue seems to be correlated to a setting on the called server. It happened for a specific API most of the time, that's why we at first thought it was an issue on the API side. Since we switched to hackney we're not having any issues, without any changes on the API side.

**Comment by josevalim** [comment] 2022-12-11 11:16
I believe Hackney does automatic retries on connection closed errors. The problem is when to retry: that could be dangerous on POST requests for example. However, we could try to see if the error happened before we sent the body (or the empty body). In such cases, it should be safe to retry.

**Comment by jadlr** [comment] 2022-12-12 21:39
Hackney is reconnecting closed connections as far as I understand it. It is not retrying requests.

**Comment by cigrainger** [comment] 2023-06-15 14:07
Just chiming in that this is happening a lot for us as well on one particular API. The API does not have any problems like this from other clients, but pretty much always kicks back `%Mint.TransportError{reason: :closed}` on the first attempt with Finch. The second attempt is pretty much always fine. We've built retries into the app but it's certainly imperfect. If I can be of any assistance in providing more information that might help figure this out, it happens reliably enough for us that that wouldn't be a problem. Please let me know if I can help.

**Comment by wojtekmach** [comment] 2023-06-15 14:12
> The API does not have any problems like this from other clients, but pretty much always kicks back %Mint.TransportError{reason: :closed} on the first attempt with Finch

I wonder if you would be able to reproduce this issue by hitting this API using Mint directly. That could give us a clue where a possible culprit might be.

**Comment by cigrainger** [comment] 2023-06-15 15:42
Okay, I can get that reliably if I wait a while and try another request. Should a `conn` 'expire'?

```elixir
** (MatchError) no match of right hand side value: {:error, %Mint.HTTP1{host: redacted, port: 9200, request: nil, streaming_request: nil, socket: #Port<0.12>, transport: Mint.Core.Transport.TCP, mode: :active, scheme_as_string: "http", requests: {[], []}, state: :closed, buffer: "", proxy_headers: [], private: %{}, log: false}, %Mint.TransportError{reason: :closed}}
    (stdlib 4.0.1) erl_eval.erl:496: :erl_eval.expr/6
    /Users/chris/Library/Application Support/livebook/autosaved/2023_06_15/14_57_38_mint_closed_gg2j.livemd#cell:ol4eldoq352ibnvzyszealwcmtjvs27g:1: (file)
```

**Comment by acco** [comment] 2024-01-16 21:44
In case you're using Req and finding yourself here (like we were): try [upgrading to the latest version](https://github.com/elixir-mint/mint/issues/417#issuecomment-1860891496)!

**Comment by MrYawe** [comment] 2024-06-04 09:56
If you are on AWS this comment may help you: https://github.com/sneako/finch/issues/272#issuecomment-2145675560
